### ISSUE TITLE
Annotations are not loaded into the project and a missing tag for test

### ISSUE THREAD

**Issue by annwhoorma** [supervisely-ecosystem/convert-yolov5-to-supervisely-format#16]
I have the following folder structure
<img width="698" alt="image" src="https://github.com/supervisely-ecosystem/convert-yolov5-to-supervisely-format/assets/34862867/4dd9753e-c055-4203-b32e-3c9f01dbe5bd">

and in the expanded state:
<img width="694" alt="image" src="https://github.com/supervisely-ecosystem/convert-yolov5-to-supervisely-format/assets/34862867/6420f062-5926-46f6-a6fd-f5af240da276">

The _data_config.yaml_ contains the following:
```yaml
train: ./10444/images/train
test: ./10444/images/test
val: ./10444/images/val


nc: 1 # number of classes
names: [particle] # class names
```

The logs show only one warning:
```
Colors not found in data_config.yaml. Colors will be generated for classes automatically.
```

Images were successfully uploaded to a project with correct tags, but
1. only 4 images were uploaded, the ones with tags "train" or "val". "test" is missing
<img width="469" alt="image" src="https://github.com/supervisely-ecosystem/convert-yolov5-to-supervisely-format/assets/34862867/d533e4a0-b8ec-455e-8311-720d8e67323f">

2. Even though I provided _labels_ folder along with _images_, supervisely says there are no annotations.
<img width="506" alt="image" src="https://github.com/supervisely-ecosystem/convert-yolov5-to-supervisely-format/assets/34862867/6e970f8d-8fab-4eee-9891-5875ee1908a9">

**Comment by iwatkot** [comment]
@annwhoorma, hello, and thanks for letting us know about the issue!

1. We've added support for test datasets to the app and now it should upload all datasets correctly. Please, ensure that you're using the latest version of the [application](https://ecosystem.supervisely.com/apps/convert-yolov5-to-supervisely-format): v2.0.0 Shifted app to new engine, added support of test datasets.
2. The issue comes from the incorrect structure specified in the data_config.yaml file.

Correct example:
```
train: ../dataset/images/train
test: ../dataset/images/test
val: ../dataset/images/val
```

Where the file structure inside the folder looks like this:
```
📦dataset
 ┣ 📂images
 ┃ ┣ 📂test
 ┃ ┃ ┗ 📜10444_atp_113-2_0004_Apr13_20.06.34.jpg
 ┃ ┣ 📂train
 ┃ ┃ ┣ 📜10444_atp_127-22_0001_Apr13_22.36.47.jpg
 ┃ ┃ ┗ 📜10444_atp_127-24_0002_Apr13_22.41.27.jpg
 ┃ ┣ 📂val
 ┃ ┃ ┣ 📜10444_atp_113-2_0007_Apr13_20.06.58.jpg
 ┃ ┃ ┗ 📜10444_atp_127-12_0006_Apr13_22.15.20.jpg
 ┣ 📂labels
 ┃ ┣ 📂test
 ┃ ┃ ┗ 📜10444_atp_113-2_0004_Apr13_20.06.34.txt
 ┃ ┣ 📂train
 ┃ ┃ ┣ 📜10444_atp_127-22_0001_Apr13_22.36.47.txt
 ┃ ┃ ┗ 📜10444_atp_127-24_0002_Apr13_22.41.27.txt
 ┃ ┣ 📂val
 ┃ ┃ ┣ 📜10444_atp_113-2_0007_Apr13_20.06.58.txt
 ┃ ┃ ┗ 📜10444_atp_127-12_0006_Apr13_22.15.20.txt
 ┗ 📜data_config.yaml
``` 

So images and labels folder are on the same level as the data_config.yaml file.
 
We're kindly asking our users to use the following support channels:
Slack: https://supervisely.slack.com/
Email: support@supervisely.com

Since we have a lot of repos and can't monitor issues in all of them.

Let me know if everything works as expected and if you have any questions in our Slack: https://supervisely.slack.com/archives/D055YTCELTF. This is a direct link for my account.

Thank you for understanding and have a good day.
Sincerely
